[project]
name = "telegram-order-python-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "strawberry-graphql[fastapi]>=0.278.0",
]
